export {
  CaretLeft,
  CaretRight,
  User,
  Buildings,
  Envelope,
  Phone,
  MagnifyingGlass,
  Bell,
  House,
  FileText,
  ShoppingBag,
  UserCircle,
  Pencil,
  CheckCircle,
  XCircle,
  Info,
  Warning,
  X,
  Check,
  Sun,
  Moon,
  Globe,
  ArrowsClockwise,
  Fingerprint,
  SealCheck,
  Lock,
  Plus,
  Camera,
  QrCode,
  Image,
  DotsThreeVertical,
  Trash,
  ThumbsUp,
  PaperPlaneRight,
  Heart,
  ChatCircle,
  Megaphone,
  Question,
  Wrench,
  Drop,
  Lightning,
  Fan,
  Elevator,
  Bug,
  Broom,
  Tree,
  ShieldCheck,
  MapPin,
  PushPin,
  CaretDown,
  SortAscending,
  Door,
  SignOut,
  Coins,
  Share,
  SquaresFour,
  WhatsappLogo,
  Flag,
  Prohibit,
  Star,
  // Facility type glyphs (resident facility booking). Non-directional —
  // these must never be mirrored in RTL.
  Barbell,
  SwimmingPool,
  ForkKnife,
  Users,
  UserMinus,
  FunnelSimple,
  Confetti,
  TennisBall,
  Basketball,
  BabyCarriage,
  Armchair,
  Car,
  // Facility rules block.
  Clock,
  CalendarBlank,
  // Poll glyphs (resident polls + ballot). Non-directional —
  // these must never be mirrored in RTL.
  ChartBar,
  Eye,
  EyeSlash,
  // Building info glyph (resident document library). Non-directional — must
  // never be mirrored in RTL.
  BookOpen,
  // Document-assistant glyphs. Non-directional — these must never be mirrored
  // in RTL: `Quotes` in particular would turn an opening mark into a closing
  // one, which reads as a typography bug rather than a mirrored icon.
  Sparkle,
  Quotes,
  // FM dashboard + notifications (T6).
  Ticket,
  UserPlus,
  ListChecks,
} from 'phosphor-react-native';
